/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser;

import node.*;
import analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTChaveDir(@SuppressWarnings("unused") TChaveDir node)
    {
        this.index = 0;
    }

    @Override
    public void caseTChaveEsq(@SuppressWarnings("unused") TChaveEsq node)
    {
        this.index = 1;
    }

    @Override
    public void caseTCocheteDir(@SuppressWarnings("unused") TCocheteDir node)
    {
        this.index = 2;
    }

    @Override
    public void caseTCocheteEsq(@SuppressWarnings("unused") TCocheteEsq node)
    {
        this.index = 3;
    }

    @Override
    public void caseTBarraDir(@SuppressWarnings("unused") TBarraDir node)
    {
        this.index = 4;
    }

    @Override
    public void caseTBarraEsq(@SuppressWarnings("unused") TBarraEsq node)
    {
        this.index = 5;
    }

    @Override
    public void caseTParenteseDir(@SuppressWarnings("unused") TParenteseDir node)
    {
        this.index = 6;
    }

    @Override
    public void caseTParenteseEsq(@SuppressWarnings("unused") TParenteseEsq node)
    {
        this.index = 7;
    }

    @Override
    public void caseTEstrela(@SuppressWarnings("unused") TEstrela node)
    {
        this.index = 8;
    }

    @Override
    public void caseTSublinhado(@SuppressWarnings("unused") TSublinhado node)
    {
        this.index = 9;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 10;
    }

    @Override
    public void caseTMenos(@SuppressWarnings("unused") TMenos node)
    {
        this.index = 11;
    }

    @Override
    public void caseTMais(@SuppressWarnings("unused") TMais node)
    {
        this.index = 12;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 13;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 14;
    }

    @Override
    public void caseTExponenciacao(@SuppressWarnings("unused") TExponenciacao node)
    {
        this.index = 15;
    }

    @Override
    public void caseTResto(@SuppressWarnings("unused") TResto node)
    {
        this.index = 16;
    }

    @Override
    public void caseTAtrib(@SuppressWarnings("unused") TAtrib node)
    {
        this.index = 17;
    }

    @Override
    public void caseTMaiorq(@SuppressWarnings("unused") TMaiorq node)
    {
        this.index = 18;
    }

    @Override
    public void caseTMenorq(@SuppressWarnings("unused") TMenorq node)
    {
        this.index = 19;
    }

    @Override
    public void caseTMaiorIgual(@SuppressWarnings("unused") TMaiorIgual node)
    {
        this.index = 20;
    }

    @Override
    public void caseTMenorIgual(@SuppressWarnings("unused") TMenorIgual node)
    {
        this.index = 21;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 22;
    }

    @Override
    public void caseTDiferente(@SuppressWarnings("unused") TDiferente node)
    {
        this.index = 23;
    }

    @Override
    public void caseTPonto(@SuppressWarnings("unused") TPonto node)
    {
        this.index = 24;
    }

    @Override
    public void caseTApostrof(@SuppressWarnings("unused") TApostrof node)
    {
        this.index = 25;
    }

    @Override
    public void caseTPrograma(@SuppressWarnings("unused") TPrograma node)
    {
        this.index = 26;
    }

    @Override
    public void caseTInicio(@SuppressWarnings("unused") TInicio node)
    {
        this.index = 27;
    }

    @Override
    public void caseTFimPonto(@SuppressWarnings("unused") TFimPonto node)
    {
        this.index = 28;
    }

    @Override
    public void caseTVar(@SuppressWarnings("unused") TVar node)
    {
        this.index = 29;
    }

    @Override
    public void caseTConstante(@SuppressWarnings("unused") TConstante node)
    {
        this.index = 30;
    }

    @Override
    public void caseTInteiro(@SuppressWarnings("unused") TInteiro node)
    {
        this.index = 31;
    }

    @Override
    public void caseTReal(@SuppressWarnings("unused") TReal node)
    {
        this.index = 32;
    }

    @Override
    public void caseTLogico(@SuppressWarnings("unused") TLogico node)
    {
        this.index = 33;
    }

    @Override
    public void caseTCaractere(@SuppressWarnings("unused") TCaractere node)
    {
        this.index = 34;
    }

    @Override
    public void caseTSe(@SuppressWarnings("unused") TSe node)
    {
        this.index = 35;
    }

    @Override
    public void caseTEntao(@SuppressWarnings("unused") TEntao node)
    {
        this.index = 36;
    }

    @Override
    public void caseTFimSe(@SuppressWarnings("unused") TFimSe node)
    {
        this.index = 37;
    }

    @Override
    public void caseTSenao(@SuppressWarnings("unused") TSenao node)
    {
        this.index = 38;
    }

    @Override
    public void caseTFimSenao(@SuppressWarnings("unused") TFimSenao node)
    {
        this.index = 39;
    }

    @Override
    public void caseTAvalie(@SuppressWarnings("unused") TAvalie node)
    {
        this.index = 40;
    }

    @Override
    public void caseTCaso(@SuppressWarnings("unused") TCaso node)
    {
        this.index = 41;
    }

    @Override
    public void caseTPadrao(@SuppressWarnings("unused") TPadrao node)
    {
        this.index = 42;
    }

    @Override
    public void caseTPara(@SuppressWarnings("unused") TPara node)
    {
        this.index = 43;
    }

    @Override
    public void caseTFaca(@SuppressWarnings("unused") TFaca node)
    {
        this.index = 44;
    }

    @Override
    public void caseTAte(@SuppressWarnings("unused") TAte node)
    {
        this.index = 45;
    }

    @Override
    public void caseTInicioPara(@SuppressWarnings("unused") TInicioPara node)
    {
        this.index = 46;
    }

    @Override
    public void caseTFimPara(@SuppressWarnings("unused") TFimPara node)
    {
        this.index = 47;
    }

    @Override
    public void caseTEnquanto(@SuppressWarnings("unused") TEnquanto node)
    {
        this.index = 48;
    }

    @Override
    public void caseTInicioEnquanto(@SuppressWarnings("unused") TInicioEnquanto node)
    {
        this.index = 49;
    }

    @Override
    public void caseTFimEnquanto(@SuppressWarnings("unused") TFimEnquanto node)
    {
        this.index = 50;
    }

    @Override
    public void caseTRepita(@SuppressWarnings("unused") TRepita node)
    {
        this.index = 51;
    }

    @Override
    public void caseTInicioRepita(@SuppressWarnings("unused") TInicioRepita node)
    {
        this.index = 52;
    }

    @Override
    public void caseTFimRepita(@SuppressWarnings("unused") TFimRepita node)
    {
        this.index = 53;
    }

    @Override
    public void caseTLeia(@SuppressWarnings("unused") TLeia node)
    {
        this.index = 54;
    }

    @Override
    public void caseTEscreva(@SuppressWarnings("unused") TEscreva node)
    {
        this.index = 55;
    }

    @Override
    public void caseTPasso(@SuppressWarnings("unused") TPasso node)
    {
        this.index = 56;
    }

    @Override
    public void caseTRetorne(@SuppressWarnings("unused") TRetorne node)
    {
        this.index = 57;
    }

    @Override
    public void caseTInterrompa(@SuppressWarnings("unused") TInterrompa node)
    {
        this.index = 58;
    }

    @Override
    public void caseTContinue(@SuppressWarnings("unused") TContinue node)
    {
        this.index = 59;
    }

    @Override
    public void caseTNao(@SuppressWarnings("unused") TNao node)
    {
        this.index = 60;
    }

    @Override
    public void caseTOu(@SuppressWarnings("unused") TOu node)
    {
        this.index = 61;
    }

    @Override
    public void caseTXou(@SuppressWarnings("unused") TXou node)
    {
        this.index = 62;
    }

    @Override
    public void caseTE(@SuppressWarnings("unused") TE node)
    {
        this.index = 63;
    }

    @Override
    public void caseTVerdade(@SuppressWarnings("unused") TVerdade node)
    {
        this.index = 64;
    }

    @Override
    public void caseTFalso(@SuppressWarnings("unused") TFalso node)
    {
        this.index = 65;
    }

    @Override
    public void caseTVetor(@SuppressWarnings("unused") TVetor node)
    {
        this.index = 66;
    }

    @Override
    public void caseTNInt(@SuppressWarnings("unused") TNInt node)
    {
        this.index = 67;
    }

    @Override
    public void caseTNReal(@SuppressWarnings("unused") TNReal node)
    {
        this.index = 68;
    }

    @Override
    public void caseTLCaractere(@SuppressWarnings("unused") TLCaractere node)
    {
        this.index = 69;
    }

    @Override
    public void caseTIdentificador(@SuppressWarnings("unused") TIdentificador node)
    {
        this.index = 70;
    }

    @Override
    public void caseTComentarioInicio(@SuppressWarnings("unused") TComentarioInicio node)
    {
        this.index = 71;
    }

    @Override
    public void caseTComentarioFim(@SuppressWarnings("unused") TComentarioFim node)
    {
        this.index = 72;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 73;
    }
}
