/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACaractereValor extends PValor
{
    private TLCaractere _lCaractere_;

    public ACaractereValor()
    {
        // Constructor
    }

    public ACaractereValor(
        @SuppressWarnings("hiding") TLCaractere _lCaractere_)
    {
        // Constructor
        setLCaractere(_lCaractere_);

    }

    @Override
    public Object clone()
    {
        return new ACaractereValor(
            cloneNode(this._lCaractere_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaractereValor(this);
    }

    public TLCaractere getLCaractere()
    {
        return this._lCaractere_;
    }

    public void setLCaractere(TLCaractere node)
    {
        if(this._lCaractere_ != null)
        {
            this._lCaractere_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lCaractere_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lCaractere_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lCaractere_ == child)
        {
            this._lCaractere_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lCaractere_ == oldChild)
        {
            setLCaractere((TLCaractere) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
