/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ADivisaoMult extends PMult
{
    private TBarraDir _barraDir_;

    public ADivisaoMult()
    {
        // Constructor
    }

    public ADivisaoMult(
        @SuppressWarnings("hiding") TBarraDir _barraDir_)
    {
        // Constructor
        setBarraDir(_barraDir_);

    }

    @Override
    public Object clone()
    {
        return new ADivisaoMult(
            cloneNode(this._barraDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivisaoMult(this);
    }

    public TBarraDir getBarraDir()
    {
        return this._barraDir_;
    }

    public void setBarraDir(TBarraDir node)
    {
        if(this._barraDir_ != null)
        {
            this._barraDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._barraDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._barraDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._barraDir_ == child)
        {
            this._barraDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._barraDir_ == oldChild)
        {
            setBarraDir((TBarraDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
