/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpParentesesFator extends PFator
{
    private TParenteseEsq _parenteseEsq_;
    private PExpAritimetrica _expAritimetrica_;
    private TParenteseDir _parenteseDir_;

    public AExpParentesesFator()
    {
        // Constructor
    }

    public AExpParentesesFator(
        @SuppressWarnings("hiding") TParenteseEsq _parenteseEsq_,
        @SuppressWarnings("hiding") PExpAritimetrica _expAritimetrica_,
        @SuppressWarnings("hiding") TParenteseDir _parenteseDir_)
    {
        // Constructor
        setParenteseEsq(_parenteseEsq_);

        setExpAritimetrica(_expAritimetrica_);

        setParenteseDir(_parenteseDir_);

    }

    @Override
    public Object clone()
    {
        return new AExpParentesesFator(
            cloneNode(this._parenteseEsq_),
            cloneNode(this._expAritimetrica_),
            cloneNode(this._parenteseDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpParentesesFator(this);
    }

    public TParenteseEsq getParenteseEsq()
    {
        return this._parenteseEsq_;
    }

    public void setParenteseEsq(TParenteseEsq node)
    {
        if(this._parenteseEsq_ != null)
        {
            this._parenteseEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseEsq_ = node;
    }

    public PExpAritimetrica getExpAritimetrica()
    {
        return this._expAritimetrica_;
    }

    public void setExpAritimetrica(PExpAritimetrica node)
    {
        if(this._expAritimetrica_ != null)
        {
            this._expAritimetrica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAritimetrica_ = node;
    }

    public TParenteseDir getParenteseDir()
    {
        return this._parenteseDir_;
    }

    public void setParenteseDir(TParenteseDir node)
    {
        if(this._parenteseDir_ != null)
        {
            this._parenteseDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parenteseEsq_)
            + toString(this._expAritimetrica_)
            + toString(this._parenteseDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parenteseEsq_ == child)
        {
            this._parenteseEsq_ = null;
            return;
        }

        if(this._expAritimetrica_ == child)
        {
            this._expAritimetrica_ = null;
            return;
        }

        if(this._parenteseDir_ == child)
        {
            this._parenteseDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parenteseEsq_ == oldChild)
        {
            setParenteseEsq((TParenteseEsq) newChild);
            return;
        }

        if(this._expAritimetrica_ == oldChild)
        {
            setExpAritimetrica((PExpAritimetrica) newChild);
            return;
        }

        if(this._parenteseDir_ == oldChild)
        {
            setParenteseDir((TParenteseDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
