/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpXouExpLogica extends PExpLogica
{
    private PExpXou _expXou_;

    public AExpXouExpLogica()
    {
        // Constructor
    }

    public AExpXouExpLogica(
        @SuppressWarnings("hiding") PExpXou _expXou_)
    {
        // Constructor
        setExpXou(_expXou_);

    }

    @Override
    public Object clone()
    {
        return new AExpXouExpLogica(
            cloneNode(this._expXou_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpXouExpLogica(this);
    }

    public PExpXou getExpXou()
    {
        return this._expXou_;
    }

    public void setExpXou(PExpXou node)
    {
        if(this._expXou_ != null)
        {
            this._expXou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expXou_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expXou_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expXou_ == child)
        {
            this._expXou_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expXou_ == oldChild)
        {
            setExpXou((PExpXou) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
