/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AListaVariaveisEscorpo extends PEscorpo
{
    private PEscorpo _escorpo_;
    private TVirgula _virgula_;
    private PVariavel _variavel_;

    public AListaVariaveisEscorpo()
    {
        // Constructor
    }

    public AListaVariaveisEscorpo(
        @SuppressWarnings("hiding") PEscorpo _escorpo_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PVariavel _variavel_)
    {
        // Constructor
        setEscorpo(_escorpo_);

        setVirgula(_virgula_);

        setVariavel(_variavel_);

    }

    @Override
    public Object clone()
    {
        return new AListaVariaveisEscorpo(
            cloneNode(this._escorpo_),
            cloneNode(this._virgula_),
            cloneNode(this._variavel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaVariaveisEscorpo(this);
    }

    public PEscorpo getEscorpo()
    {
        return this._escorpo_;
    }

    public void setEscorpo(PEscorpo node)
    {
        if(this._escorpo_ != null)
        {
            this._escorpo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escorpo_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PVariavel getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PVariavel node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escorpo_)
            + toString(this._virgula_)
            + toString(this._variavel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escorpo_ == child)
        {
            this._escorpo_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escorpo_ == oldChild)
        {
            setEscorpo((PEscorpo) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._variavel_ == oldChild)
        {
            setVariavel((PVariavel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
