/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMenorMaiorExpComparativa extends PExpComparativa
{
    private PExpMenorMaior _expMenorMaior_;

    public AMenorMaiorExpComparativa()
    {
        // Constructor
    }

    public AMenorMaiorExpComparativa(
        @SuppressWarnings("hiding") PExpMenorMaior _expMenorMaior_)
    {
        // Constructor
        setExpMenorMaior(_expMenorMaior_);

    }

    @Override
    public Object clone()
    {
        return new AMenorMaiorExpComparativa(
            cloneNode(this._expMenorMaior_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorMaiorExpComparativa(this);
    }

    public PExpMenorMaior getExpMenorMaior()
    {
        return this._expMenorMaior_;
    }

    public void setExpMenorMaior(PExpMenorMaior node)
    {
        if(this._expMenorMaior_ != null)
        {
            this._expMenorMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMenorMaior_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expMenorMaior_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expMenorMaior_ == child)
        {
            this._expMenorMaior_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expMenorMaior_ == oldChild)
        {
            setExpMenorMaior((PExpMenorMaior) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
