/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOuLogicoExpLogica extends PExpLogica
{
    private PExpLogica _expLogica_;
    private TOu _ou_;
    private PExpXou _expXou_;

    public AOuLogicoExpLogica()
    {
        // Constructor
    }

    public AOuLogicoExpLogica(
        @SuppressWarnings("hiding") PExpLogica _expLogica_,
        @SuppressWarnings("hiding") TOu _ou_,
        @SuppressWarnings("hiding") PExpXou _expXou_)
    {
        // Constructor
        setExpLogica(_expLogica_);

        setOu(_ou_);

        setExpXou(_expXou_);

    }

    @Override
    public Object clone()
    {
        return new AOuLogicoExpLogica(
            cloneNode(this._expLogica_),
            cloneNode(this._ou_),
            cloneNode(this._expXou_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOuLogicoExpLogica(this);
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    public TOu getOu()
    {
        return this._ou_;
    }

    public void setOu(TOu node)
    {
        if(this._ou_ != null)
        {
            this._ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ou_ = node;
    }

    public PExpXou getExpXou()
    {
        return this._expXou_;
    }

    public void setExpXou(PExpXou node)
    {
        if(this._expXou_ != null)
        {
            this._expXou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expXou_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica_)
            + toString(this._ou_)
            + toString(this._expXou_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        if(this._ou_ == child)
        {
            this._ou_ = null;
            return;
        }

        if(this._expXou_ == child)
        {
            this._expXou_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        if(this._ou_ == oldChild)
        {
            setOu((TOu) newChild);
            return;
        }

        if(this._expXou_ == oldChild)
        {
            setExpXou((PExpXou) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
