/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOuxLogicoExpXou extends PExpXou
{
    private PExpXou _expXou_;
    private TXou _xou_;
    private PExpE _expE_;

    public AOuxLogicoExpXou()
    {
        // Constructor
    }

    public AOuxLogicoExpXou(
        @SuppressWarnings("hiding") PExpXou _expXou_,
        @SuppressWarnings("hiding") TXou _xou_,
        @SuppressWarnings("hiding") PExpE _expE_)
    {
        // Constructor
        setExpXou(_expXou_);

        setXou(_xou_);

        setExpE(_expE_);

    }

    @Override
    public Object clone()
    {
        return new AOuxLogicoExpXou(
            cloneNode(this._expXou_),
            cloneNode(this._xou_),
            cloneNode(this._expE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOuxLogicoExpXou(this);
    }

    public PExpXou getExpXou()
    {
        return this._expXou_;
    }

    public void setExpXou(PExpXou node)
    {
        if(this._expXou_ != null)
        {
            this._expXou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expXou_ = node;
    }

    public TXou getXou()
    {
        return this._xou_;
    }

    public void setXou(TXou node)
    {
        if(this._xou_ != null)
        {
            this._xou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xou_ = node;
    }

    public PExpE getExpE()
    {
        return this._expE_;
    }

    public void setExpE(PExpE node)
    {
        if(this._expE_ != null)
        {
            this._expE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expXou_)
            + toString(this._xou_)
            + toString(this._expE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expXou_ == child)
        {
            this._expXou_ = null;
            return;
        }

        if(this._xou_ == child)
        {
            this._xou_ = null;
            return;
        }

        if(this._expE_ == child)
        {
            this._expE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expXou_ == oldChild)
        {
            setExpXou((PExpXou) newChild);
            return;
        }

        if(this._xou_ == oldChild)
        {
            setXou((TXou) newChild);
            return;
        }

        if(this._expE_ == oldChild)
        {
            setExpE((PExpE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
