/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AParentesesComparacaoTermoLogico extends PTermoLogico
{
    private PExpComparativa _expComparativa_;

    public AParentesesComparacaoTermoLogico()
    {
        // Constructor
    }

    public AParentesesComparacaoTermoLogico(
        @SuppressWarnings("hiding") PExpComparativa _expComparativa_)
    {
        // Constructor
        setExpComparativa(_expComparativa_);

    }

    @Override
    public Object clone()
    {
        return new AParentesesComparacaoTermoLogico(
            cloneNode(this._expComparativa_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParentesesComparacaoTermoLogico(this);
    }

    public PExpComparativa getExpComparativa()
    {
        return this._expComparativa_;
    }

    public void setExpComparativa(PExpComparativa node)
    {
        if(this._expComparativa_ != null)
        {
            this._expComparativa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expComparativa_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expComparativa_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expComparativa_ == child)
        {
            this._expComparativa_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expComparativa_ == oldChild)
        {
            setExpComparativa((PExpComparativa) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
