/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASeBlocoSeBloco extends PSeBloco
{
    private TSe _se_;
    private TParenteseEsq _parenteseEsq_;
    private PExpLogica _expLogica_;
    private TParenteseDir _parenteseDir_;
    private TEntao _entao_;
    private PComando _comando_;
    private PSenaoBloco _senaoBloco_;
    private TFimSe _fimSe_;

    public ASeBlocoSeBloco()
    {
        // Constructor
    }

    public ASeBlocoSeBloco(
        @SuppressWarnings("hiding") TSe _se_,
        @SuppressWarnings("hiding") TParenteseEsq _parenteseEsq_,
        @SuppressWarnings("hiding") PExpLogica _expLogica_,
        @SuppressWarnings("hiding") TParenteseDir _parenteseDir_,
        @SuppressWarnings("hiding") TEntao _entao_,
        @SuppressWarnings("hiding") PComando _comando_,
        @SuppressWarnings("hiding") PSenaoBloco _senaoBloco_,
        @SuppressWarnings("hiding") TFimSe _fimSe_)
    {
        // Constructor
        setSe(_se_);

        setParenteseEsq(_parenteseEsq_);

        setExpLogica(_expLogica_);

        setParenteseDir(_parenteseDir_);

        setEntao(_entao_);

        setComando(_comando_);

        setSenaoBloco(_senaoBloco_);

        setFimSe(_fimSe_);

    }

    @Override
    public Object clone()
    {
        return new ASeBlocoSeBloco(
            cloneNode(this._se_),
            cloneNode(this._parenteseEsq_),
            cloneNode(this._expLogica_),
            cloneNode(this._parenteseDir_),
            cloneNode(this._entao_),
            cloneNode(this._comando_),
            cloneNode(this._senaoBloco_),
            cloneNode(this._fimSe_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeBlocoSeBloco(this);
    }

    public TSe getSe()
    {
        return this._se_;
    }

    public void setSe(TSe node)
    {
        if(this._se_ != null)
        {
            this._se_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._se_ = node;
    }

    public TParenteseEsq getParenteseEsq()
    {
        return this._parenteseEsq_;
    }

    public void setParenteseEsq(TParenteseEsq node)
    {
        if(this._parenteseEsq_ != null)
        {
            this._parenteseEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseEsq_ = node;
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    public TParenteseDir getParenteseDir()
    {
        return this._parenteseDir_;
    }

    public void setParenteseDir(TParenteseDir node)
    {
        if(this._parenteseDir_ != null)
        {
            this._parenteseDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteseDir_ = node;
    }

    public TEntao getEntao()
    {
        return this._entao_;
    }

    public void setEntao(TEntao node)
    {
        if(this._entao_ != null)
        {
            this._entao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entao_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    public PSenaoBloco getSenaoBloco()
    {
        return this._senaoBloco_;
    }

    public void setSenaoBloco(PSenaoBloco node)
    {
        if(this._senaoBloco_ != null)
        {
            this._senaoBloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoBloco_ = node;
    }

    public TFimSe getFimSe()
    {
        return this._fimSe_;
    }

    public void setFimSe(TFimSe node)
    {
        if(this._fimSe_ != null)
        {
            this._fimSe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fimSe_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._se_)
            + toString(this._parenteseEsq_)
            + toString(this._expLogica_)
            + toString(this._parenteseDir_)
            + toString(this._entao_)
            + toString(this._comando_)
            + toString(this._senaoBloco_)
            + toString(this._fimSe_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._se_ == child)
        {
            this._se_ = null;
            return;
        }

        if(this._parenteseEsq_ == child)
        {
            this._parenteseEsq_ = null;
            return;
        }

        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        if(this._parenteseDir_ == child)
        {
            this._parenteseDir_ = null;
            return;
        }

        if(this._entao_ == child)
        {
            this._entao_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        if(this._senaoBloco_ == child)
        {
            this._senaoBloco_ = null;
            return;
        }

        if(this._fimSe_ == child)
        {
            this._fimSe_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._se_ == oldChild)
        {
            setSe((TSe) newChild);
            return;
        }

        if(this._parenteseEsq_ == oldChild)
        {
            setParenteseEsq((TParenteseEsq) newChild);
            return;
        }

        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        if(this._parenteseDir_ == oldChild)
        {
            setParenteseDir((TParenteseDir) newChild);
            return;
        }

        if(this._entao_ == oldChild)
        {
            setEntao((TEntao) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        if(this._senaoBloco_ == oldChild)
        {
            setSenaoBloco((PSenaoBloco) newChild);
            return;
        }

        if(this._fimSe_ == oldChild)
        {
            setFimSe((TFimSe) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
