/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASenaoBlocoSenaoBloco extends PSenaoBloco
{
    private TSenao _senao_;
    private PComando _comando_;
    private TFimSenao _fimSenao_;

    public ASenaoBlocoSenaoBloco()
    {
        // Constructor
    }

    public ASenaoBlocoSenaoBloco(
        @SuppressWarnings("hiding") TSenao _senao_,
        @SuppressWarnings("hiding") PComando _comando_,
        @SuppressWarnings("hiding") TFimSenao _fimSenao_)
    {
        // Constructor
        setSenao(_senao_);

        setComando(_comando_);

        setFimSenao(_fimSenao_);

    }

    @Override
    public Object clone()
    {
        return new ASenaoBlocoSenaoBloco(
            cloneNode(this._senao_),
            cloneNode(this._comando_),
            cloneNode(this._fimSenao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASenaoBlocoSenaoBloco(this);
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    public TFimSenao getFimSenao()
    {
        return this._fimSenao_;
    }

    public void setFimSenao(TFimSenao node)
    {
        if(this._fimSenao_ != null)
        {
            this._fimSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fimSenao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._senao_)
            + toString(this._comando_)
            + toString(this._fimSenao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        if(this._fimSenao_ == child)
        {
            this._fimSenao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        if(this._fimSenao_ == oldChild)
        {
            setFimSenao((TFimSenao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
