/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AVetorVariavel extends PVariavel
{
    private TIdentificador _identificador_;
    private TCocheteEsq _cocheteEsq_;
    private TNInt _nInt_;
    private TCocheteDir _cocheteDir_;

    public AVetorVariavel()
    {
        // Constructor
    }

    public AVetorVariavel(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") TCocheteEsq _cocheteEsq_,
        @SuppressWarnings("hiding") TNInt _nInt_,
        @SuppressWarnings("hiding") TCocheteDir _cocheteDir_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setCocheteEsq(_cocheteEsq_);

        setNInt(_nInt_);

        setCocheteDir(_cocheteDir_);

    }

    @Override
    public Object clone()
    {
        return new AVetorVariavel(
            cloneNode(this._identificador_),
            cloneNode(this._cocheteEsq_),
            cloneNode(this._nInt_),
            cloneNode(this._cocheteDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVetorVariavel(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public TCocheteEsq getCocheteEsq()
    {
        return this._cocheteEsq_;
    }

    public void setCocheteEsq(TCocheteEsq node)
    {
        if(this._cocheteEsq_ != null)
        {
            this._cocheteEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cocheteEsq_ = node;
    }

    public TNInt getNInt()
    {
        return this._nInt_;
    }

    public void setNInt(TNInt node)
    {
        if(this._nInt_ != null)
        {
            this._nInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nInt_ = node;
    }

    public TCocheteDir getCocheteDir()
    {
        return this._cocheteDir_;
    }

    public void setCocheteDir(TCocheteDir node)
    {
        if(this._cocheteDir_ != null)
        {
            this._cocheteDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cocheteDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._cocheteEsq_)
            + toString(this._nInt_)
            + toString(this._cocheteDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._cocheteEsq_ == child)
        {
            this._cocheteEsq_ = null;
            return;
        }

        if(this._nInt_ == child)
        {
            this._nInt_ = null;
            return;
        }

        if(this._cocheteDir_ == child)
        {
            this._cocheteDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._cocheteEsq_ == oldChild)
        {
            setCocheteEsq((TCocheteEsq) newChild);
            return;
        }

        if(this._nInt_ == oldChild)
        {
            setNInt((TNInt) newChild);
            return;
        }

        if(this._cocheteDir_ == oldChild)
        {
            setCocheteDir((TCocheteDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
