/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TFimSenao extends Token
{
    public TFimSenao()
    {
        super.setText("fim senao");
    }

    public TFimSenao(int line, int pos)
    {
        super.setText("fim senao");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFimSenao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFimSenao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFimSenao text.");
    }
}
