/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TInicioEnquanto extends Token
{
    public TInicioEnquanto()
    {
        super.setText("inicio enquanto");
    }

    public TInicioEnquanto(int line, int pos)
    {
        super.setText("inicio enquanto");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInicioEnquanto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInicioEnquanto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInicioEnquanto text.");
    }
}
