/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexer;

import java.io.*;
import node.*;

@SuppressWarnings("nls")
public class Lexer
{
	   protected Token token;
	    protected State state = State.NORMAL;

	    private IPushbackReader in;
	    private int line;
	    private int pos;
	    private boolean cr;
	    private boolean eof;
	    private final StringBuffer text = new StringBuffer();
		private String texto = new String();;
	    private TComentarioCorpo comentario;
	    private int contador; 
	    private LexerException error;
	    
	    
    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
    	//Aqui vamos iniciar com o estado que me permite parar o laço do filtro.
    	if(state.equals(State.COMENTARIO_ANINHADO))
		{
    		//Aqui analisamos o código para saber se existe comentários balanceados
    		if(token instanceof TComentarioInicio){//Se encontrarmos um token  TComentarioInicio
    			contador++;						  //vamos incrementar o contador.
    		}
    		if(token instanceof TComentarioFim){//Se encontrarmos aqui um token TComentarioFim
    			contador--;						//vamos decrementar o contador.
    		}
    	
    		//aqui é só uma forma de reiniciar o token TComentarioCorpo.
    		if(comentario == null){
    			comentario = new TComentarioCorpo("");
    		
    		}
    	
    		//Caso o Comentario aninhado não esteja balanceado.
    		if(contador != 0){
    			//Gera um erro se o Comentario aninhado não estiver balanceado e se for encontrado o fim do arquivo.
    			if(!(token instanceof TComentarioInicio) && !(token instanceof TComentarioCorpo) && !(token instanceof TComentarioFim)&& !(token instanceof TLCaractere)){
    				InvalidToken tokenInvalido = new InvalidToken(token.getText());
    				error = new LexerException(tokenInvalido, "Falta um */  ou /* para completar o comentario");
    				error.printStackTrace();
    			}else{//Se ainda existir algum token ele o empilha no token comentárioCorpo
    				texto += token.getText();
    				token = null;
    			}
    		}else{//Se o comentario estiver balançeado , encerramos o loop, e inserimos todo o comentário no token comentárioCorpo
    				comentario.setText(texto);	
    				token = comentario;
    				comentario = null;
    				state = State.NORMAL;
    			}
		}
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 72:
                        {
                            @SuppressWarnings("hiding") Token token = new72(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 73:
                        {
                            @SuppressWarnings("hiding") Token token = new73(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO_ANINHADO; break;
                                case 0: state = State.COMENTARIO_ANINHADO; break;
                            }
                            return token;
                        }
                    case 74:
                        {
                            @SuppressWarnings("hiding") Token token = new74(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO_ANINHADO; break;
                            }
                            return token;
                        }
                    case 75:
                        {
                            @SuppressWarnings("hiding") Token token = new75(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO_ANINHADO; break;
                            }
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChaveDir(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChaveEsq(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCocheteDir(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCocheteEsq(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBarraDir(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBarraEsq(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParenteseDir(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParenteseEsq(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEstrela(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSublinhado(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMais(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoVirgula(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoisPontos(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TExponenciacao(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TResto(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtrib(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorq(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorq(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorIgual(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgual(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TApostrof(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrograma(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(line, pos); }
    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimPonto(text, line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVar(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstante(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiro(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLogico(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaractere(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEntao(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimSe(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimSenao(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAvalie(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaso(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPadrao(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPara(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFaca(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAte(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicioPara(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimPara(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicioEnquanto(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimEnquanto(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRepita(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicioRepita(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimRepita(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeia(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscreva(line, pos); }
    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPasso(line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRetorne(line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInterrompa(line, pos); }
    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TContinue(line, pos); }
    Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNao(line, pos); }
    Token new61(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new62(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXou(line, pos); }
    Token new63(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new64(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVerdade(line, pos); }
    Token new65(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalso(line, pos); }
    Token new66(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVetor(line, pos); }
    Token new67(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNInt(text, line, pos); }
    Token new68(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNReal(text, line, pos); }
    Token new69(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLCaractere(text, line, pos); }
    Token new70(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentario(text, line, pos); }
    Token new71(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBrancos(text, line, pos); }
    Token new72(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentificador(text, line, pos); }
    Token new73(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioInicio(text, line, pos); }
    Token new74(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioFim(text, line, pos); }
    Token new75(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioCorpo(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {37, 37, 5}, {39, 39, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {58, 58, 16}, {59, 59, 17}, {60, 60, 18}, {61, 61, 19}, {62, 62, 20}, {65, 90, 21}, {91, 91, 22}, {92, 92, 23}, {93, 93, 24}, {94, 94, 25}, {95, 95, 26}, {97, 97, 27}, {98, 98, 28}, {99, 99, 29}, {100, 100, 28}, {101, 101, 30}, {102, 102, 31}, {103, 104, 28}, {105, 105, 32}, {106, 107, 28}, {108, 108, 33}, {109, 109, 28}, {110, 110, 34}, {111, 111, 35}, {112, 112, 36}, {113, 113, 28}, {114, 114, 37}, {115, 115, 38}, {116, 117, 28}, {118, 118, 39}, {119, 119, 28}, {120, 120, 40}, {121, 122, 28}, {123, 123, 41}, {125, 125, 42}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 43}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {{0, 9, 44}, {11, 127, 44}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{42, 42, 45}, {47, 47, 46}, },
            {{44, 44, 47}, {48, 57, 48}, },
            {},
            {},
            {{45, 45, 49}, {61, 61, 50}, {62, 62, 51}, },
            {},
            {{61, 61, 52}, },
            {{48, 57, 53}, {65, 90, 54}, {95, 95, 55}, {97, 122, 56}, },
            {},
            {},
            {},
            {},
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 115, 56}, {116, 116, 57}, {117, 117, 56}, {118, 118, 58}, {119, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 59}, {98, 110, 56}, {111, 111, 60}, {112, 122, 56}, },
            {{48, 95, -23}, {97, 109, 56}, {110, 110, 61}, {111, 114, 56}, {115, 115, 62}, {116, 122, 56}, },
            {{48, 95, -23}, {97, 97, 63}, {98, 104, 56}, {105, 105, 64}, {106, 122, 56}, },
            {{48, 109, -32}, {110, 110, 65}, {111, 122, 56}, },
            {{48, 95, -23}, {97, 100, 56}, {101, 101, 66}, {102, 110, 56}, {111, 111, 67}, {112, 122, 56}, },
            {{48, 95, -23}, {97, 97, 68}, {98, 122, 56}, },
            {{48, 95, -23}, {97, 116, 56}, {117, 117, 69}, {118, 122, 56}, },
            {{48, 95, -23}, {97, 97, 70}, {98, 113, 56}, {114, 114, 71}, {115, 122, 56}, },
            {{48, 100, -35}, {101, 101, 72}, {102, 122, 56}, },
            {{48, 100, -35}, {101, 101, 73}, {102, 122, 56}, },
            {{48, 95, -23}, {97, 97, 74}, {98, 100, 56}, {101, 101, 75}, {102, 122, 56}, },
            {{48, 95, -23}, {97, 110, 56}, {111, 111, 76}, {112, 122, 56}, },
            {},
            {},
            {{9, 32, -2}, },
            {{39, 39, 77}, },
            {},
            {{0, 9, 78}, {11, 12, 78}, {14, 127, 78}, },
            {{48, 57, 79}, },
            {{48, 57, 48}, },
            {},
            {},
            {},
            {},
            {{48, 57, 53}, {65, 90, 80}, {95, 95, 81}, {97, 122, 82}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 100, -35}, {101, 101, 83}, {102, 122, 56}, },
            {{48, 95, -23}, {97, 97, 84}, {98, 122, 56}, },
            {{48, 95, -23}, {97, 113, 56}, {114, 114, 85}, {115, 115, 86}, {116, 122, 56}, },
            {{48, 109, -32}, {110, 110, 87}, {111, 122, 56}, },
            {{48, 95, -23}, {97, 112, 56}, {113, 113, 88}, {114, 115, 56}, {116, 116, 89}, {117, 122, 56}, },
            {{48, 95, -23}, {97, 98, 56}, {99, 99, 90}, {100, 122, 56}, },
            {{48, 98, -64}, {99, 99, 91}, {100, 107, 56}, {108, 108, 92}, {109, 122, 56}, },
            {{48, 95, -23}, {97, 108, 56}, {109, 109, 93}, {110, 122, 56}, },
            {{48, 95, -23}, {97, 104, 56}, {105, 105, 94}, {106, 115, 56}, {116, 116, 95}, {117, 122, 56}, },
            {{48, 104, -67}, {105, 105, 96}, {106, 122, 56}, },
            {{48, 95, -23}, {97, 102, 56}, {103, 103, 97}, {104, 122, 56}, },
            {{48, 110, -42}, {111, 111, 98}, {112, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 99, 56}, {100, 100, 99}, {101, 113, 56}, {114, 114, 100}, {115, 115, 101}, {116, 122, 56}, },
            {{48, 110, -42}, {111, 111, 102}, {112, 122, 56}, },
            {{48, 95, -23}, {97, 97, 103}, {98, 111, 56}, {112, 112, 104}, {113, 115, 56}, {116, 116, 105}, {117, 122, 56}, },
            {{48, 109, -32}, {110, 110, 106}, {111, 122, 56}, },
            {{48, 113, -61}, {114, 114, 107}, {115, 122, 56}, },
            {{48, 113, -61}, {114, 114, 108}, {115, 115, 56}, {116, 116, 109}, {117, 122, 56}, },
            {{48, 116, -37}, {117, 117, 110}, {118, 122, 56}, },
            {},
            {{0, 127, -48}, },
            {{48, 57, 79}, },
            {{48, 122, -55}, },
            {{48, 122, -55}, },
            {{48, 122, -55}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 107, 56}, {108, 108, 111}, {109, 122, 56}, },
            {{48, 95, -23}, {97, 97, 112}, {98, 122, 56}, },
            {{48, 110, -42}, {111, 111, 113}, {112, 122, 56}, },
            {{48, 95, -23}, {97, 114, 56}, {115, 115, 114}, {116, 116, 115}, {117, 122, 56}, },
            {{48, 116, -37}, {117, 117, 116}, {118, 122, 56}, },
            {{48, 95, -23}, {97, 97, 117}, {98, 122, 56}, },
            {{48, 113, -61}, {114, 114, 118}, {115, 122, 56}, },
            {{48, 95, -23}, {97, 97, 119}, {98, 122, 56}, },
            {{48, 114, -89}, {115, 115, 120}, {116, 122, 56}, },
            {{32, 32, 121}, {46, 46, 122}, {48, 122, -23}, },
            {{48, 98, -64}, {99, 99, 123}, {100, 122, 56}, },
            {{48, 100, -35}, {101, 101, 124}, {102, 122, 56}, },
            {{48, 95, -23}, {97, 97, 125}, {98, 122, 56}, },
            {{48, 104, -67}, {105, 105, 126}, {106, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 113, -61}, {114, 114, 127}, {115, 122, 56}, },
            {{48, 95, -23}, {97, 97, 128}, {98, 122, 56}, },
            {{48, 114, -89}, {115, 115, 129}, {116, 122, 56}, },
            {{48, 102, -69}, {103, 103, 130}, {104, 122, 56}, },
            {{48, 107, -86}, {108, 108, 131}, {109, 122, 56}, },
            {{48, 104, -67}, {105, 105, 132}, {106, 122, 56}, },
            {{48, 110, -42}, {111, 111, 133}, {112, 122, 56}, },
            {{48, 95, -23}, {97, 97, 134}, {98, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 99, -72}, {100, 100, 135}, {101, 122, 56}, },
            {{48, 110, -42}, {111, 111, 136}, {112, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 104, -67}, {105, 105, 137}, {106, 122, 56}, },
            {{48, 98, -64}, {99, 99, 138}, {100, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 115, -29}, {116, 116, 139}, {117, 122, 56}, },
            {{48, 104, -67}, {105, 105, 140}, {106, 122, 56}, },
            {{48, 95, -23}, {97, 97, 141}, {98, 122, 56}, },
            {{48, 110, -42}, {111, 111, 142}, {112, 122, 56}, },
            {{48, 100, -35}, {101, 101, 143}, {102, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 110, -42}, {111, 111, 144}, {112, 122, 56}, },
            {{101, 101, 145}, {112, 112, 146}, {114, 114, 147}, {115, 115, 148}, },
            {},
            {{48, 104, -67}, {105, 105, 149}, {106, 122, 56}, },
            {{48, 104, -67}, {105, 105, 150}, {106, 113, 56}, {114, 114, 151}, {115, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 98, -64}, {99, 99, 152}, {100, 122, 56}, },
            {{48, 95, -23}, {97, 97, 153}, {98, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 110, -42}, {111, 111, 154}, {112, 122, 56}, },
            {{48, 113, -61}, {114, 114, 155}, {115, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 115, -29}, {116, 116, 156}, {117, 122, 56}, },
            {{48, 113, -61}, {114, 114, 157}, {115, 122, 56}, },
            {{48, 110, -42}, {111, 111, 158}, {112, 122, 56}, },
            {{48, 95, -23}, {97, 97, 159}, {98, 122, 56}, },
            {{48, 113, -61}, {114, 114, 160}, {115, 122, 56}, },
            {{48, 100, -35}, {101, 101, 161}, {102, 122, 56}, },
            {{48, 115, -29}, {116, 116, 162}, {117, 122, 56}, },
            {{48, 95, -23}, {97, 97, 163}, {98, 122, 56}, },
            {{48, 109, -32}, {110, 110, 164}, {111, 122, 56}, },
            {{48, 109, -32}, {110, 110, 165}, {111, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 117, 56}, {118, 118, 166}, {119, 122, 56}, },
            {{48, 122, -23}, },
            {{110, 110, 167}, },
            {{97, 97, 168}, },
            {{101, 101, 169}, },
            {{101, 101, 170}, },
            {{48, 110, -42}, {111, 111, 171}, {112, 122, 56}, },
            {{48, 113, -61}, {114, 114, 172}, {115, 122, 56}, },
            {{48, 113, -61}, {114, 114, 173}, {115, 122, 56}, },
            {{48, 110, -42}, {111, 111, 174}, {112, 122, 56}, },
            {{48, 110, -42}, {111, 111, 175}, {112, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 176}, {98, 122, 56}, },
            {{48, 95, -23}, {97, 97, 177}, {98, 122, 56}, },
            {{48, 109, -32}, {110, 110, 178}, {111, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 99, -72}, {100, 100, 179}, {101, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 100, -35}, {101, 101, 180}, {102, 122, 56}, },
            {{48, 109, -32}, {110, 110, 181}, {111, 122, 56}, },
            {{48, 116, -37}, {117, 117, 182}, {118, 122, 56}, },
            {{48, 115, -29}, {116, 116, 183}, {117, 122, 56}, },
            {{48, 95, -23}, {97, 97, 184}, {98, 122, 56}, },
            {{113, 113, 185}, },
            {{114, 114, 186}, },
            {{112, 112, 187}, },
            {{110, 110, 188}, },
            {{32, 32, 189}, {48, 122, -23}, },
            {{48, 110, -42}, {111, 111, 190}, {112, 122, 56}, },
            {{48, 110, -42}, {111, 111, 191}, {112, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 108, -66}, {109, 109, 192}, {110, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 100, -35}, {101, 101, 193}, {102, 122, 56}, },
            {{48, 100, -35}, {101, 101, 194}, {102, 122, 56}, },
            {{48, 113, -61}, {114, 114, 195}, {115, 122, 56}, },
            {{48, 115, -29}, {116, 116, 196}, {117, 122, 56}, },
            {{48, 100, -35}, {101, 101, 197}, {102, 122, 56}, },
            {{48, 110, -42}, {111, 111, 198}, {112, 122, 56}, },
            {{48, 122, -23}, },
            {{117, 117, 199}, },
            {{97, 97, 200}, },
            {{105, 105, 201}, },
            {{97, 97, 202}, },
            {{101, 101, 203}, {112, 112, 204}, {114, 114, 205}, },
            {{48, 122, -23}, },
            {{48, 108, -66}, {109, 109, 206}, {110, 122, 56}, },
            {{48, 95, -23}, {97, 97, 207}, {98, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 100, -35}, {101, 101, 208}, {102, 122, 56}, },
            {{48, 100, -35}, {101, 101, 209}, {102, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{97, 97, 210}, },
            {},
            {{116, 116, 211}, },
            {{111, 111, 212}, },
            {{110, 110, 213}, },
            {{97, 97, 214}, },
            {{101, 101, 215}, },
            {{48, 95, -23}, {97, 111, 56}, {112, 112, 216}, {113, 122, 56}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{110, 110, 217}, },
            {{97, 97, 218}, },
            {},
            {{113, 113, 219}, },
            {{114, 114, 220}, },
            {{112, 112, 221}, },
            {{48, 95, -23}, {97, 97, 222}, {98, 122, 56}, },
            {{116, 116, 223}, },
            {},
            {{117, 117, 224}, },
            {{97, 97, 225}, },
            {{105, 105, 226}, },
            {{48, 122, -23}, },
            {{111, 111, 227}, },
            {{97, 97, 228}, },
            {},
            {{116, 116, 229}, },
            {},
            {{110, 110, 230}, },
            {{97, 97, 231}, },
            {{116, 116, 232}, },
            {},
            {{111, 111, 233}, },
            {},
        }
        { // COMENTARIO_ANINHADO
            {{0, 36, 1}, {37, 37, 2}, {38, 38, 1}, {39, 39, 3}, {40, 40, 4}, {41, 41, 5}, {42, 42, 6}, {43, 43, 7}, {44, 44, 8}, {45, 45, 9}, {46, 46, 10}, {47, 47, 11}, {48, 57, 12}, {58, 58, 13}, {59, 59, 14}, {60, 60, 15}, {61, 61, 16}, {62, 62, 17}, {63, 90, 1}, {91, 91, 18}, {92, 92, 19}, {93, 93, 20}, {94, 94, 21}, {95, 95, 22}, {96, 96, 1}, {97, 97, 23}, {98, 98, 1}, {99, 99, 24}, {100, 100, 1}, {101, 101, 25}, {102, 102, 26}, {103, 104, 1}, {105, 105, 27}, {106, 107, 1}, {108, 108, 28}, {109, 109, 1}, {110, 110, 29}, {111, 111, 30}, {112, 112, 31}, {113, 113, 1}, {114, 114, 32}, {115, 115, 33}, {116, 117, 1}, {118, 118, 34}, {119, 119, 1}, {120, 120, 35}, {121, 122, 1}, {123, 123, 36}, {124, 124, 1}, {125, 125, 37}, {126, 127, 1}, },
            {{0, 41, 1}, {43, 46, 1}, {48, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 9, 38}, {10, 10, 1}, {11, 41, 38}, {42, 42, 39}, {43, 46, 38}, {47, 47, 39}, {48, 127, 38}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{47, 47, 40}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{42, 42, 41}, {47, 47, 42}, },
            {{0, 41, 1}, {43, 43, 1}, {44, 44, 43}, {45, 46, 1}, {48, 57, 44}, {58, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 41, 1}, {43, 44, 1}, {45, 45, 45}, {46, 46, 1}, {48, 60, 1}, {61, 61, 46}, {62, 62, 47}, {63, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 60, 1}, {61, 61, 48}, {62, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 115, 1}, {116, 116, 49}, {117, 117, 1}, {118, 118, 50}, {119, 127, 1}, },
            {{0, 46, -3}, {48, 96, 1}, {97, 97, 51}, {98, 110, 1}, {111, 111, 52}, {112, 127, 1}, },
            {{0, 46, -3}, {48, 109, 1}, {110, 110, 53}, {111, 114, 1}, {115, 115, 54}, {116, 127, 1}, },
            {{0, 96, -26}, {97, 97, 55}, {98, 104, 1}, {105, 105, 56}, {106, 127, 1}, },
            {{0, 109, -27}, {110, 110, 57}, {111, 127, 1}, },
            {{0, 46, -3}, {48, 100, 1}, {101, 101, 58}, {102, 110, 1}, {111, 111, 59}, {112, 127, 1}, },
            {{0, 96, -26}, {97, 97, 60}, {98, 127, 1}, },
            {{0, 46, -3}, {48, 116, 1}, {117, 117, 61}, {118, 127, 1}, },
            {{0, 96, -26}, {97, 97, 62}, {98, 113, 1}, {114, 114, 63}, {115, 127, 1}, },
            {{0, 100, -30}, {101, 101, 64}, {102, 127, 1}, },
            {{0, 100, -30}, {101, 101, 65}, {102, 127, 1}, },
            {{0, 96, -26}, {97, 97, 66}, {98, 100, 1}, {101, 101, 67}, {102, 127, 1}, },
            {{0, 46, -3}, {48, 110, 1}, {111, 111, 68}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 38, 1}, {39, 39, 69}, {40, 41, 1}, {43, 127, -3}, },
            {{39, 39, 70}, },
            {},
            {},
            {{0, 9, 71}, {11, 12, 71}, {14, 127, 71}, },
            {{0, 46, -3}, {48, 57, 72}, {58, 127, 1}, },
            {{0, 46, -3}, {48, 127, -14}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 100, -30}, {101, 101, 73}, {102, 127, 1}, },
            {{0, 96, -26}, {97, 97, 74}, {98, 127, 1}, },
            {{0, 46, -3}, {48, 113, 1}, {114, 114, 75}, {115, 115, 76}, {116, 127, 1}, },
            {{0, 109, -27}, {110, 110, 77}, {111, 127, 1}, },
            {{0, 46, -3}, {48, 112, 1}, {113, 113, 78}, {114, 115, 1}, {116, 116, 79}, {117, 127, 1}, },
            {{0, 46, -3}, {48, 98, 1}, {99, 99, 80}, {100, 127, 1}, },
            {{0, 98, -56}, {99, 99, 81}, {100, 107, 1}, {108, 108, 82}, {109, 127, 1}, },
            {{0, 46, -3}, {48, 108, 1}, {109, 109, 83}, {110, 127, 1}, },
            {{0, 46, -3}, {48, 104, 1}, {105, 105, 84}, {106, 115, 1}, {116, 116, 85}, {117, 127, 1}, },
            {{0, 104, -59}, {105, 105, 86}, {106, 127, 1}, },
            {{0, 46, -3}, {48, 102, 1}, {103, 103, 87}, {104, 127, 1}, },
            {{0, 110, -37}, {111, 111, 88}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 99, 1}, {100, 100, 89}, {101, 113, 1}, {114, 114, 90}, {115, 115, 91}, {116, 127, 1}, },
            {{0, 110, -37}, {111, 111, 92}, {112, 127, 1}, },
            {{0, 96, -26}, {97, 97, 93}, {98, 111, 1}, {112, 112, 94}, {113, 115, 1}, {116, 116, 95}, {117, 127, 1}, },
            {{0, 109, -27}, {110, 110, 96}, {111, 127, 1}, },
            {{0, 113, -53}, {114, 114, 97}, {115, 127, 1}, },
            {{0, 113, -53}, {114, 114, 98}, {115, 115, 1}, {116, 116, 99}, {117, 127, 1}, },
            {{0, 116, -32}, {117, 117, 100}, {118, 127, 1}, },
            {{0, 127, -3}, },
            {},
            {{0, 127, -44}, },
            {{0, 127, -45}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 107, 1}, {108, 108, 101}, {109, 127, 1}, },
            {{0, 96, -26}, {97, 97, 102}, {98, 127, 1}, },
            {{0, 110, -37}, {111, 111, 103}, {112, 127, 1}, },
            {{0, 46, -3}, {48, 114, 1}, {115, 115, 104}, {116, 116, 105}, {117, 127, 1}, },
            {{0, 116, -32}, {117, 117, 106}, {118, 127, 1}, },
            {{0, 96, -26}, {97, 97, 107}, {98, 127, 1}, },
            {{0, 113, -53}, {114, 114, 108}, {115, 127, 1}, },
            {{0, 96, -26}, {97, 97, 109}, {98, 127, 1}, },
            {{0, 114, -79}, {115, 115, 110}, {116, 127, 1}, },
            {{0, 31, 1}, {32, 32, 111}, {33, 41, 1}, {43, 45, 1}, {46, 46, 112}, {48, 127, 1}, },
            {{0, 98, -56}, {99, 99, 113}, {100, 127, 1}, },
            {{0, 100, -30}, {101, 101, 114}, {102, 127, 1}, },
            {{0, 96, -26}, {97, 97, 115}, {98, 127, 1}, },
            {{0, 104, -59}, {105, 105, 116}, {106, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 113, -53}, {114, 114, 117}, {115, 127, 1}, },
            {{0, 96, -26}, {97, 97, 118}, {98, 127, 1}, },
            {{0, 114, -79}, {115, 115, 119}, {116, 127, 1}, },
            {{0, 102, -61}, {103, 103, 120}, {104, 127, 1}, },
            {{0, 107, -76}, {108, 108, 121}, {109, 127, 1}, },
            {{0, 104, -59}, {105, 105, 122}, {106, 127, 1}, },
            {{0, 110, -37}, {111, 111, 123}, {112, 127, 1}, },
            {{0, 96, -26}, {97, 97, 124}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 99, -64}, {100, 100, 125}, {101, 127, 1}, },
            {{0, 110, -37}, {111, 111, 126}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 104, -59}, {105, 105, 127}, {106, 127, 1}, },
            {{0, 98, -56}, {99, 99, 128}, {100, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 115, -25}, {116, 116, 129}, {117, 127, 1}, },
            {{0, 104, -59}, {105, 105, 130}, {106, 127, 1}, },
            {{0, 96, -26}, {97, 97, 131}, {98, 127, 1}, },
            {{0, 110, -37}, {111, 111, 132}, {112, 127, 1}, },
            {{0, 100, -30}, {101, 101, 133}, {102, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 110, -37}, {111, 111, 134}, {112, 127, 1}, },
            {{0, 100, -30}, {101, 101, 135}, {102, 111, 1}, {112, 112, 136}, {113, 113, 1}, {114, 114, 137}, {115, 115, 138}, {116, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 104, -59}, {105, 105, 139}, {106, 127, 1}, },
            {{0, 104, -59}, {105, 105, 140}, {106, 113, 1}, {114, 114, 141}, {115, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 98, -56}, {99, 99, 142}, {100, 127, 1}, },
            {{0, 96, -26}, {97, 97, 143}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 110, -37}, {111, 111, 144}, {112, 127, 1}, },
            {{0, 113, -53}, {114, 114, 145}, {115, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 115, -25}, {116, 116, 146}, {117, 127, 1}, },
            {{0, 113, -53}, {114, 114, 147}, {115, 127, 1}, },
            {{0, 110, -37}, {111, 111, 148}, {112, 127, 1}, },
            {{0, 96, -26}, {97, 97, 149}, {98, 127, 1}, },
            {{0, 113, -53}, {114, 114, 150}, {115, 127, 1}, },
            {{0, 100, -30}, {101, 101, 151}, {102, 127, 1}, },
            {{0, 115, -25}, {116, 116, 152}, {117, 127, 1}, },
            {{0, 96, -26}, {97, 97, 153}, {98, 127, 1}, },
            {{0, 109, -27}, {110, 110, 154}, {111, 127, 1}, },
            {{0, 109, -27}, {110, 110, 155}, {111, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 117, 1}, {118, 118, 156}, {119, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 109, -27}, {110, 110, 157}, {111, 127, 1}, },
            {{0, 96, -26}, {97, 97, 158}, {98, 127, 1}, },
            {{0, 100, -30}, {101, 101, 159}, {102, 127, 1}, },
            {{0, 100, -30}, {101, 101, 160}, {102, 127, 1}, },
            {{0, 110, -37}, {111, 111, 161}, {112, 127, 1}, },
            {{0, 113, -53}, {114, 114, 162}, {115, 127, 1}, },
            {{0, 113, -53}, {114, 114, 163}, {115, 127, 1}, },
            {{0, 110, -37}, {111, 111, 164}, {112, 127, 1}, },
            {{0, 110, -37}, {111, 111, 165}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 96, -26}, {97, 97, 166}, {98, 127, 1}, },
            {{0, 96, -26}, {97, 97, 167}, {98, 127, 1}, },
            {{0, 109, -27}, {110, 110, 168}, {111, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 99, -64}, {100, 100, 169}, {101, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 100, -30}, {101, 101, 170}, {102, 127, 1}, },
            {{0, 109, -27}, {110, 110, 171}, {111, 127, 1}, },
            {{0, 116, -32}, {117, 117, 172}, {118, 127, 1}, },
            {{0, 115, -25}, {116, 116, 173}, {117, 127, 1}, },
            {{0, 96, -26}, {97, 97, 174}, {98, 127, 1}, },
            {{0, 112, -55}, {113, 113, 175}, {114, 127, 1}, },
            {{0, 113, -53}, {114, 114, 176}, {115, 127, 1}, },
            {{0, 46, -3}, {48, 111, 1}, {112, 112, 177}, {113, 127, 1}, },
            {{0, 109, -27}, {110, 110, 178}, {111, 127, 1}, },
            {{0, 31, 1}, {32, 32, 179}, {33, 41, 1}, {43, 127, -3}, },
            {{0, 110, -37}, {111, 111, 180}, {112, 127, 1}, },
            {{0, 110, -37}, {111, 111, 181}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 108, -58}, {109, 109, 182}, {110, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 100, -30}, {101, 101, 183}, {102, 127, 1}, },
            {{0, 100, -30}, {101, 101, 184}, {102, 127, 1}, },
            {{0, 113, -53}, {114, 114, 185}, {115, 127, 1}, },
            {{0, 115, -25}, {116, 116, 186}, {117, 127, 1}, },
            {{0, 100, -30}, {101, 101, 187}, {102, 127, 1}, },
            {{0, 110, -37}, {111, 111, 188}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 116, -32}, {117, 117, 189}, {118, 127, 1}, },
            {{0, 96, -26}, {97, 97, 190}, {98, 127, 1}, },
            {{0, 104, -59}, {105, 105, 191}, {106, 127, 1}, },
            {{0, 96, -26}, {97, 97, 192}, {98, 127, 1}, },
            {{0, 100, -30}, {101, 101, 193}, {102, 111, 1}, {112, 112, 194}, {113, 113, 1}, {114, 114, 195}, {115, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 108, -58}, {109, 109, 196}, {110, 127, 1}, },
            {{0, 96, -26}, {97, 97, 197}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 100, -30}, {101, 101, 198}, {102, 127, 1}, },
            {{0, 100, -30}, {101, 101, 199}, {102, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 96, -26}, {97, 97, 200}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 115, -25}, {116, 116, 201}, {117, 127, 1}, },
            {{0, 110, -37}, {111, 111, 202}, {112, 127, 1}, },
            {{0, 109, -27}, {110, 110, 203}, {111, 127, 1}, },
            {{0, 96, -26}, {97, 97, 204}, {98, 127, 1}, },
            {{0, 100, -30}, {101, 101, 205}, {102, 127, 1}, },
            {{0, 111, -161}, {112, 112, 206}, {113, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 109, -27}, {110, 110, 207}, {111, 127, 1}, },
            {{0, 96, -26}, {97, 97, 208}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 112, -55}, {113, 113, 209}, {114, 127, 1}, },
            {{0, 113, -53}, {114, 114, 210}, {115, 127, 1}, },
            {{0, 111, -161}, {112, 112, 211}, {113, 127, 1}, },
            {{0, 96, -26}, {97, 97, 212}, {98, 127, 1}, },
            {{0, 115, -25}, {116, 116, 213}, {117, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 116, -32}, {117, 117, 214}, {118, 127, 1}, },
            {{0, 96, -26}, {97, 97, 215}, {98, 127, 1}, },
            {{0, 104, -59}, {105, 105, 216}, {106, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 110, -37}, {111, 111, 217}, {112, 127, 1}, },
            {{0, 96, -26}, {97, 97, 218}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 115, -25}, {116, 116, 219}, {117, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 109, -27}, {110, 110, 220}, {111, 127, 1}, },
            {{0, 96, -26}, {97, 97, 221}, {98, 127, 1}, },
            {{0, 115, -25}, {116, 116, 222}, {117, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 110, -37}, {111, 111, 223}, {112, 127, 1}, },
            {{0, 127, -3}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 71, 71, 71, 71, 16, 25, 6, 7, 8, 12, 10, 11, 24, 4, 67, 14, 13, 19, 22, 18, 72, 3, 5, 2, 15, 9, 72, 72, 72, 63, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 1, 0, 71, -1, 73, 70, -1, 67, 17, 21, 23, 20, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 61, 72, 72, 72, 35, 72, 72, 72, 69, 70, 68, 72, 72, 72, 45, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 60, 72, 72, 72, 72, 72, 72, 72, 72, 29, 72, 72, 62, 72, 72, 41, 72, 72, 72, 72, 72, 44, 72, -1, 28, 72, 72, 54, 72, 72, 43, 72, 72, 32, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 36, 72, 65, -1, -1, -1, -1, 72, 72, 72, 72, 72, 56, 72, 72, 72, 38, 72, 66, 40, 72, 72, 72, 72, 72, -1, -1, -1, 37, 27, 72, 72, 33, 42, 72, 51, 72, 72, 72, 72, 72, 72, 55, -1, -1, -1, -1, -1, 31, 72, 72, 57, 64, 72, 72, 59, 48, -1, 47, -1, -1, -1, -1, -1, 72, 26, 34, 30, -1, -1, 39, -1, -1, -1, 72, -1, 53, -1, -1, -1, 58, -1, -1, 46, -1, 50, -1, -1, -1, 52, -1, 49, },
        // COMENTARIO_ANINHADO
        {75, 75, 16, 25, 6, 7, 8, 12, 10, 11, 24, 4, 67, 14, 13, 19, 22, 18, 3, 5, 2, 15, 9, 75, 75, 63, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 1, 0, 75, -1, 74, 73, 70, 75, 67, 17, 21, 23, 20, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 61, 75, 75, 75, 35, 75, 75, 75, 69, 69, 70, 68, 45, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 60, 75, 75, 75, 75, 75, 75, 75, 75, 29, 75, 75, 62, 75, 75, 41, 75, 75, 75, 75, 75, 44, 75, 75, 28, 75, 75, 54, 75, 75, 43, 75, 75, 32, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 36, 75, 65, 75, 75, 75, 75, 75, 75, 75, 75, 75, 56, 75, 75, 75, 38, 75, 66, 40, 75, 75, 75, 75, 75, 75, 75, 75, 37, 27, 75, 75, 33, 42, 75, 51, 75, 75, 75, 75, 75, 75, 55, 75, 75, 75, 75, 75, 31, 75, 75, 57, 64, 75, 75, 59, 48, 75, 47, 75, 75, 75, 75, 75, 75, 26, 34, 30, 75, 75, 39, 75, 75, 75, 75, 75, 53, 75, 75, 75, 58, 75, 75, 46, 75, 50, 75, 75, 75, 52, 75, 49, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMENTARIO_ANINHADO = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
