/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexer;

import java.io.*;
import node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 72:
                        {
                            @SuppressWarnings("hiding") Token token = new72(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 73:
                        {
                            @SuppressWarnings("hiding") Token token = new73(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO_ANINHADO; break;
                                case 0: state = State.COMENTARIO_ANINHADO; break;
                            }
                            return token;
                        }
                    case 74:
                        {
                            @SuppressWarnings("hiding") Token token = new74(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO_ANINHADO; break;
                            }
                            return token;
                        }
                    case 75:
                        {
                            @SuppressWarnings("hiding") Token token = new75(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO_ANINHADO; break;
                            }
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChaveDir(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChaveEsq(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCocheteDir(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCocheteEsq(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBarraDir(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBarraEsq(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParenteseDir(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParenteseEsq(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEstrela(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSublinhado(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMais(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoVirgula(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoisPontos(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TExponenciacao(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TResto(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtrib(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorq(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorq(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorIgual(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgual(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TApostrof(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrograma(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(line, pos); }
    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimPonto(text, line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVar(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstante(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiro(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLogico(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaractere(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEntao(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimSe(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimSenao(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAvalie(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaso(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPadrao(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPara(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFaca(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAte(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicioPara(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimPara(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicioEnquanto(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimEnquanto(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRepita(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicioRepita(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimRepita(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeia(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscreva(line, pos); }
    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPasso(line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRetorne(line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInterrompa(line, pos); }
    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TContinue(line, pos); }
    Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNao(line, pos); }
    Token new61(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new62(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXou(line, pos); }
    Token new63(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new64(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVerdade(line, pos); }
    Token new65(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalso(line, pos); }
    Token new66(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVetor(line, pos); }
    Token new67(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNInt(text, line, pos); }
    Token new68(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNReal(text, line, pos); }
    Token new69(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLCaractere(text, line, pos); }
    Token new70(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentario(text, line, pos); }
    Token new71(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBrancos(text, line, pos); }
    Token new72(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentificador(text, line, pos); }
    Token new73(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioInicio(text, line, pos); }
    Token new74(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioFim(text, line, pos); }
    Token new75(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioCorpo(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {37, 37, 5}, {39, 39, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {58, 58, 16}, {59, 59, 17}, {60, 60, 18}, {61, 61, 19}, {62, 62, 20}, {65, 90, 21}, {91, 91, 22}, {92, 92, 23}, {93, 93, 24}, {94, 94, 25}, {95, 95, 26}, {97, 97, 27}, {98, 98, 28}, {99, 99, 29}, {100, 100, 28}, {101, 101, 30}, {102, 102, 31}, {103, 104, 28}, {105, 105, 32}, {106, 107, 28}, {108, 108, 33}, {109, 109, 28}, {110, 110, 34}, {111, 111, 35}, {112, 112, 36}, {113, 113, 28}, {114, 114, 37}, {115, 115, 38}, {116, 117, 28}, {118, 118, 39}, {119, 119, 28}, {120, 120, 40}, {121, 122, 28}, {123, 123, 41}, {125, 125, 42}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 43}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {{0, 9, 44}, {11, 127, 44}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{42, 42, 45}, {47, 47, 46}, },
            {{44, 44, 47}, {48, 57, 15}, },
            {},
            {},
            {{45, 45, 48}, {61, 61, 49}, {62, 62, 50}, },
            {},
            {{61, 61, 51}, },
            {{48, 57, 52}, {65, 90, 53}, {95, 95, 54}, {97, 122, 55}, },
            {},
            {},
            {},
            {},
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 115, 55}, {116, 116, 56}, {117, 117, 55}, {118, 118, 57}, {119, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 58}, {98, 110, 55}, {111, 111, 59}, {112, 122, 55}, },
            {{48, 95, -23}, {97, 109, 55}, {110, 110, 60}, {111, 114, 55}, {115, 115, 61}, {116, 122, 55}, },
            {{48, 95, -23}, {97, 97, 62}, {98, 104, 55}, {105, 105, 63}, {106, 122, 55}, },
            {{48, 109, -32}, {110, 110, 64}, {111, 122, 55}, },
            {{48, 95, -23}, {97, 100, 55}, {101, 101, 65}, {102, 110, 55}, {111, 111, 66}, {112, 122, 55}, },
            {{48, 95, -23}, {97, 97, 67}, {98, 122, 55}, },
            {{48, 95, -23}, {97, 116, 55}, {117, 117, 68}, {118, 122, 55}, },
            {{48, 95, -23}, {97, 97, 69}, {98, 113, 55}, {114, 114, 70}, {115, 122, 55}, },
            {{48, 100, -35}, {101, 101, 71}, {102, 122, 55}, },
            {{48, 100, -35}, {101, 101, 72}, {102, 122, 55}, },
            {{48, 95, -23}, {97, 97, 73}, {98, 100, 55}, {101, 101, 74}, {102, 122, 55}, },
            {{48, 95, -23}, {97, 110, 55}, {111, 111, 75}, {112, 122, 55}, },
            {},
            {},
            {{9, 32, -2}, },
            {{39, 39, 76}, },
            {},
            {{0, 9, 77}, {11, 12, 77}, {14, 127, 77}, },
            {{48, 57, 78}, },
            {},
            {},
            {},
            {},
            {{48, 57, 52}, {65, 90, 79}, {95, 95, 80}, {97, 122, 81}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 100, -35}, {101, 101, 82}, {102, 122, 55}, },
            {{48, 95, -23}, {97, 97, 83}, {98, 122, 55}, },
            {{48, 95, -23}, {97, 113, 55}, {114, 114, 84}, {115, 115, 85}, {116, 122, 55}, },
            {{48, 109, -32}, {110, 110, 86}, {111, 122, 55}, },
            {{48, 95, -23}, {97, 112, 55}, {113, 113, 87}, {114, 115, 55}, {116, 116, 88}, {117, 122, 55}, },
            {{48, 95, -23}, {97, 98, 55}, {99, 99, 89}, {100, 122, 55}, },
            {{48, 98, -63}, {99, 99, 90}, {100, 107, 55}, {108, 108, 91}, {109, 122, 55}, },
            {{48, 95, -23}, {97, 108, 55}, {109, 109, 92}, {110, 122, 55}, },
            {{48, 95, -23}, {97, 104, 55}, {105, 105, 93}, {106, 115, 55}, {116, 116, 94}, {117, 122, 55}, },
            {{48, 104, -66}, {105, 105, 95}, {106, 122, 55}, },
            {{48, 95, -23}, {97, 102, 55}, {103, 103, 96}, {104, 122, 55}, },
            {{48, 110, -42}, {111, 111, 97}, {112, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 99, 55}, {100, 100, 98}, {101, 113, 55}, {114, 114, 99}, {115, 115, 100}, {116, 122, 55}, },
            {{48, 110, -42}, {111, 111, 101}, {112, 122, 55}, },
            {{48, 95, -23}, {97, 97, 102}, {98, 111, 55}, {112, 112, 103}, {113, 115, 55}, {116, 116, 104}, {117, 122, 55}, },
            {{48, 109, -32}, {110, 110, 105}, {111, 122, 55}, },
            {{48, 113, -60}, {114, 114, 106}, {115, 122, 55}, },
            {{48, 113, -60}, {114, 114, 107}, {115, 115, 55}, {116, 116, 108}, {117, 122, 55}, },
            {{48, 116, -37}, {117, 117, 109}, {118, 122, 55}, },
            {},
            {{0, 127, -48}, },
            {{48, 57, 78}, },
            {{48, 122, -54}, },
            {{48, 122, -54}, },
            {{48, 122, -54}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 107, 55}, {108, 108, 110}, {109, 122, 55}, },
            {{48, 95, -23}, {97, 97, 111}, {98, 122, 55}, },
            {{48, 110, -42}, {111, 111, 112}, {112, 122, 55}, },
            {{48, 95, -23}, {97, 114, 55}, {115, 115, 113}, {116, 116, 114}, {117, 122, 55}, },
            {{48, 116, -37}, {117, 117, 115}, {118, 122, 55}, },
            {{48, 95, -23}, {97, 97, 116}, {98, 122, 55}, },
            {{48, 113, -60}, {114, 114, 117}, {115, 122, 55}, },
            {{48, 95, -23}, {97, 97, 118}, {98, 122, 55}, },
            {{48, 114, -88}, {115, 115, 119}, {116, 122, 55}, },
            {{32, 32, 120}, {46, 46, 121}, {48, 122, -23}, },
            {{48, 98, -63}, {99, 99, 122}, {100, 122, 55}, },
            {{48, 100, -35}, {101, 101, 123}, {102, 122, 55}, },
            {{48, 95, -23}, {97, 97, 124}, {98, 122, 55}, },
            {{48, 104, -66}, {105, 105, 125}, {106, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 113, -60}, {114, 114, 126}, {115, 122, 55}, },
            {{48, 95, -23}, {97, 97, 127}, {98, 122, 55}, },
            {{48, 114, -88}, {115, 115, 128}, {116, 122, 55}, },
            {{48, 102, -68}, {103, 103, 129}, {104, 122, 55}, },
            {{48, 107, -85}, {108, 108, 130}, {109, 122, 55}, },
            {{48, 104, -66}, {105, 105, 131}, {106, 122, 55}, },
            {{48, 110, -42}, {111, 111, 132}, {112, 122, 55}, },
            {{48, 95, -23}, {97, 97, 133}, {98, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 99, -71}, {100, 100, 134}, {101, 122, 55}, },
            {{48, 110, -42}, {111, 111, 135}, {112, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 104, -66}, {105, 105, 136}, {106, 122, 55}, },
            {{48, 98, -63}, {99, 99, 137}, {100, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 115, -29}, {116, 116, 138}, {117, 122, 55}, },
            {{48, 104, -66}, {105, 105, 139}, {106, 122, 55}, },
            {{48, 95, -23}, {97, 97, 140}, {98, 122, 55}, },
            {{48, 110, -42}, {111, 111, 141}, {112, 122, 55}, },
            {{48, 100, -35}, {101, 101, 142}, {102, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 110, -42}, {111, 111, 143}, {112, 122, 55}, },
            {{101, 101, 144}, {112, 112, 145}, {114, 114, 146}, {115, 115, 147}, },
            {},
            {{48, 104, -66}, {105, 105, 148}, {106, 122, 55}, },
            {{48, 104, -66}, {105, 105, 149}, {106, 113, 55}, {114, 114, 150}, {115, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 98, -63}, {99, 99, 151}, {100, 122, 55}, },
            {{48, 95, -23}, {97, 97, 152}, {98, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 110, -42}, {111, 111, 153}, {112, 122, 55}, },
            {{48, 113, -60}, {114, 114, 154}, {115, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 115, -29}, {116, 116, 155}, {117, 122, 55}, },
            {{48, 113, -60}, {114, 114, 156}, {115, 122, 55}, },
            {{48, 110, -42}, {111, 111, 157}, {112, 122, 55}, },
            {{48, 95, -23}, {97, 97, 158}, {98, 122, 55}, },
            {{48, 113, -60}, {114, 114, 159}, {115, 122, 55}, },
            {{48, 100, -35}, {101, 101, 160}, {102, 122, 55}, },
            {{48, 115, -29}, {116, 116, 161}, {117, 122, 55}, },
            {{48, 95, -23}, {97, 97, 162}, {98, 122, 55}, },
            {{48, 109, -32}, {110, 110, 163}, {111, 122, 55}, },
            {{48, 109, -32}, {110, 110, 164}, {111, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 117, 55}, {118, 118, 165}, {119, 122, 55}, },
            {{48, 122, -23}, },
            {{110, 110, 166}, },
            {{97, 97, 167}, },
            {{101, 101, 168}, },
            {{101, 101, 169}, },
            {{48, 110, -42}, {111, 111, 170}, {112, 122, 55}, },
            {{48, 113, -60}, {114, 114, 171}, {115, 122, 55}, },
            {{48, 113, -60}, {114, 114, 172}, {115, 122, 55}, },
            {{48, 110, -42}, {111, 111, 173}, {112, 122, 55}, },
            {{48, 110, -42}, {111, 111, 174}, {112, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 175}, {98, 122, 55}, },
            {{48, 95, -23}, {97, 97, 176}, {98, 122, 55}, },
            {{48, 109, -32}, {110, 110, 177}, {111, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 99, -71}, {100, 100, 178}, {101, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 100, -35}, {101, 101, 179}, {102, 122, 55}, },
            {{48, 109, -32}, {110, 110, 180}, {111, 122, 55}, },
            {{48, 116, -37}, {117, 117, 181}, {118, 122, 55}, },
            {{48, 115, -29}, {116, 116, 182}, {117, 122, 55}, },
            {{48, 95, -23}, {97, 97, 183}, {98, 122, 55}, },
            {{113, 113, 184}, },
            {{114, 114, 185}, },
            {{112, 112, 186}, },
            {{110, 110, 187}, },
            {{32, 32, 188}, {48, 122, -23}, },
            {{48, 110, -42}, {111, 111, 189}, {112, 122, 55}, },
            {{48, 110, -42}, {111, 111, 190}, {112, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 108, -65}, {109, 109, 191}, {110, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 100, -35}, {101, 101, 192}, {102, 122, 55}, },
            {{48, 100, -35}, {101, 101, 193}, {102, 122, 55}, },
            {{48, 113, -60}, {114, 114, 194}, {115, 122, 55}, },
            {{48, 115, -29}, {116, 116, 195}, {117, 122, 55}, },
            {{48, 100, -35}, {101, 101, 196}, {102, 122, 55}, },
            {{48, 110, -42}, {111, 111, 197}, {112, 122, 55}, },
            {{48, 122, -23}, },
            {{117, 117, 198}, },
            {{97, 97, 199}, },
            {{105, 105, 200}, },
            {{97, 97, 201}, },
            {{101, 101, 202}, {112, 112, 203}, {114, 114, 204}, },
            {{48, 122, -23}, },
            {{48, 108, -65}, {109, 109, 205}, {110, 122, 55}, },
            {{48, 95, -23}, {97, 97, 206}, {98, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 100, -35}, {101, 101, 207}, {102, 122, 55}, },
            {{48, 100, -35}, {101, 101, 208}, {102, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{97, 97, 209}, },
            {},
            {{116, 116, 210}, },
            {{111, 111, 211}, },
            {{110, 110, 212}, },
            {{97, 97, 213}, },
            {{101, 101, 214}, },
            {{48, 95, -23}, {97, 111, 55}, {112, 112, 215}, {113, 122, 55}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{110, 110, 216}, },
            {{97, 97, 217}, },
            {},
            {{113, 113, 218}, },
            {{114, 114, 219}, },
            {{112, 112, 220}, },
            {{48, 95, -23}, {97, 97, 221}, {98, 122, 55}, },
            {{116, 116, 222}, },
            {},
            {{117, 117, 223}, },
            {{97, 97, 224}, },
            {{105, 105, 225}, },
            {{48, 122, -23}, },
            {{111, 111, 226}, },
            {{97, 97, 227}, },
            {},
            {{116, 116, 228}, },
            {},
            {{110, 110, 229}, },
            {{97, 97, 230}, },
            {{116, 116, 231}, },
            {},
            {{111, 111, 232}, },
            {},
        }
        { // COMENTARIO_ANINHADO
            {{0, 36, 1}, {37, 37, 2}, {38, 38, 1}, {39, 39, 3}, {40, 40, 4}, {41, 41, 5}, {42, 42, 6}, {43, 43, 7}, {44, 44, 8}, {45, 45, 9}, {46, 46, 10}, {47, 47, 11}, {48, 57, 12}, {58, 58, 13}, {59, 59, 14}, {60, 60, 15}, {61, 61, 16}, {62, 62, 17}, {63, 90, 1}, {91, 91, 18}, {92, 92, 19}, {93, 93, 20}, {94, 94, 21}, {95, 95, 22}, {96, 96, 1}, {97, 97, 23}, {98, 98, 1}, {99, 99, 24}, {100, 100, 1}, {101, 101, 25}, {102, 102, 26}, {103, 104, 1}, {105, 105, 27}, {106, 107, 1}, {108, 108, 28}, {109, 109, 1}, {110, 110, 29}, {111, 111, 30}, {112, 112, 31}, {113, 113, 1}, {114, 114, 32}, {115, 115, 33}, {116, 117, 1}, {118, 118, 34}, {119, 119, 1}, {120, 120, 35}, {121, 122, 1}, {123, 123, 36}, {124, 124, 1}, {125, 125, 37}, {126, 127, 1}, },
            {{0, 41, 1}, {43, 46, 1}, {48, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 9, 38}, {10, 10, 1}, {11, 41, 38}, {42, 42, 39}, {43, 46, 38}, {47, 47, 39}, {48, 127, 38}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{47, 47, 40}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{42, 42, 41}, {47, 47, 42}, },
            {{0, 41, 1}, {43, 43, 1}, {44, 44, 43}, {45, 46, 1}, {48, 57, 12}, {58, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 41, 1}, {43, 44, 1}, {45, 45, 44}, {46, 46, 1}, {48, 60, 1}, {61, 61, 45}, {62, 62, 46}, {63, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 60, 1}, {61, 61, 47}, {62, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 115, 1}, {116, 116, 48}, {117, 117, 1}, {118, 118, 49}, {119, 127, 1}, },
            {{0, 46, -3}, {48, 96, 1}, {97, 97, 50}, {98, 110, 1}, {111, 111, 51}, {112, 127, 1}, },
            {{0, 46, -3}, {48, 109, 1}, {110, 110, 52}, {111, 114, 1}, {115, 115, 53}, {116, 127, 1}, },
            {{0, 96, -26}, {97, 97, 54}, {98, 104, 1}, {105, 105, 55}, {106, 127, 1}, },
            {{0, 109, -27}, {110, 110, 56}, {111, 127, 1}, },
            {{0, 46, -3}, {48, 100, 1}, {101, 101, 57}, {102, 110, 1}, {111, 111, 58}, {112, 127, 1}, },
            {{0, 96, -26}, {97, 97, 59}, {98, 127, 1}, },
            {{0, 46, -3}, {48, 116, 1}, {117, 117, 60}, {118, 127, 1}, },
            {{0, 96, -26}, {97, 97, 61}, {98, 113, 1}, {114, 114, 62}, {115, 127, 1}, },
            {{0, 100, -30}, {101, 101, 63}, {102, 127, 1}, },
            {{0, 100, -30}, {101, 101, 64}, {102, 127, 1}, },
            {{0, 96, -26}, {97, 97, 65}, {98, 100, 1}, {101, 101, 66}, {102, 127, 1}, },
            {{0, 46, -3}, {48, 110, 1}, {111, 111, 67}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 38, 1}, {39, 39, 68}, {40, 41, 1}, {43, 127, -3}, },
            {{39, 39, 69}, },
            {},
            {},
            {{0, 9, 70}, {11, 12, 70}, {14, 127, 70}, },
            {{0, 46, -3}, {48, 57, 71}, {58, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 100, -30}, {101, 101, 72}, {102, 127, 1}, },
            {{0, 96, -26}, {97, 97, 73}, {98, 127, 1}, },
            {{0, 46, -3}, {48, 113, 1}, {114, 114, 74}, {115, 115, 75}, {116, 127, 1}, },
            {{0, 109, -27}, {110, 110, 76}, {111, 127, 1}, },
            {{0, 46, -3}, {48, 112, 1}, {113, 113, 77}, {114, 115, 1}, {116, 116, 78}, {117, 127, 1}, },
            {{0, 46, -3}, {48, 98, 1}, {99, 99, 79}, {100, 127, 1}, },
            {{0, 98, -55}, {99, 99, 80}, {100, 107, 1}, {108, 108, 81}, {109, 127, 1}, },
            {{0, 46, -3}, {48, 108, 1}, {109, 109, 82}, {110, 127, 1}, },
            {{0, 46, -3}, {48, 104, 1}, {105, 105, 83}, {106, 115, 1}, {116, 116, 84}, {117, 127, 1}, },
            {{0, 104, -58}, {105, 105, 85}, {106, 127, 1}, },
            {{0, 46, -3}, {48, 102, 1}, {103, 103, 86}, {104, 127, 1}, },
            {{0, 110, -37}, {111, 111, 87}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 99, 1}, {100, 100, 88}, {101, 113, 1}, {114, 114, 89}, {115, 115, 90}, {116, 127, 1}, },
            {{0, 110, -37}, {111, 111, 91}, {112, 127, 1}, },
            {{0, 96, -26}, {97, 97, 92}, {98, 111, 1}, {112, 112, 93}, {113, 115, 1}, {116, 116, 94}, {117, 127, 1}, },
            {{0, 109, -27}, {110, 110, 95}, {111, 127, 1}, },
            {{0, 113, -52}, {114, 114, 96}, {115, 127, 1}, },
            {{0, 113, -52}, {114, 114, 97}, {115, 115, 1}, {116, 116, 98}, {117, 127, 1}, },
            {{0, 116, -32}, {117, 117, 99}, {118, 127, 1}, },
            {{0, 127, -3}, },
            {},
            {{0, 127, -44}, },
            {{0, 127, -45}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 107, 1}, {108, 108, 100}, {109, 127, 1}, },
            {{0, 96, -26}, {97, 97, 101}, {98, 127, 1}, },
            {{0, 110, -37}, {111, 111, 102}, {112, 127, 1}, },
            {{0, 46, -3}, {48, 114, 1}, {115, 115, 103}, {116, 116, 104}, {117, 127, 1}, },
            {{0, 116, -32}, {117, 117, 105}, {118, 127, 1}, },
            {{0, 96, -26}, {97, 97, 106}, {98, 127, 1}, },
            {{0, 113, -52}, {114, 114, 107}, {115, 127, 1}, },
            {{0, 96, -26}, {97, 97, 108}, {98, 127, 1}, },
            {{0, 114, -78}, {115, 115, 109}, {116, 127, 1}, },
            {{0, 31, 1}, {32, 32, 110}, {33, 41, 1}, {43, 45, 1}, {46, 46, 111}, {48, 127, 1}, },
            {{0, 98, -55}, {99, 99, 112}, {100, 127, 1}, },
            {{0, 100, -30}, {101, 101, 113}, {102, 127, 1}, },
            {{0, 96, -26}, {97, 97, 114}, {98, 127, 1}, },
            {{0, 104, -58}, {105, 105, 115}, {106, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 113, -52}, {114, 114, 116}, {115, 127, 1}, },
            {{0, 96, -26}, {97, 97, 117}, {98, 127, 1}, },
            {{0, 114, -78}, {115, 115, 118}, {116, 127, 1}, },
            {{0, 102, -60}, {103, 103, 119}, {104, 127, 1}, },
            {{0, 107, -75}, {108, 108, 120}, {109, 127, 1}, },
            {{0, 104, -58}, {105, 105, 121}, {106, 127, 1}, },
            {{0, 110, -37}, {111, 111, 122}, {112, 127, 1}, },
            {{0, 96, -26}, {97, 97, 123}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 99, -63}, {100, 100, 124}, {101, 127, 1}, },
            {{0, 110, -37}, {111, 111, 125}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 104, -58}, {105, 105, 126}, {106, 127, 1}, },
            {{0, 98, -55}, {99, 99, 127}, {100, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 115, -25}, {116, 116, 128}, {117, 127, 1}, },
            {{0, 104, -58}, {105, 105, 129}, {106, 127, 1}, },
            {{0, 96, -26}, {97, 97, 130}, {98, 127, 1}, },
            {{0, 110, -37}, {111, 111, 131}, {112, 127, 1}, },
            {{0, 100, -30}, {101, 101, 132}, {102, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 110, -37}, {111, 111, 133}, {112, 127, 1}, },
            {{0, 100, -30}, {101, 101, 134}, {102, 111, 1}, {112, 112, 135}, {113, 113, 1}, {114, 114, 136}, {115, 115, 137}, {116, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 104, -58}, {105, 105, 138}, {106, 127, 1}, },
            {{0, 104, -58}, {105, 105, 139}, {106, 113, 1}, {114, 114, 140}, {115, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 98, -55}, {99, 99, 141}, {100, 127, 1}, },
            {{0, 96, -26}, {97, 97, 142}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 110, -37}, {111, 111, 143}, {112, 127, 1}, },
            {{0, 113, -52}, {114, 114, 144}, {115, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 115, -25}, {116, 116, 145}, {117, 127, 1}, },
            {{0, 113, -52}, {114, 114, 146}, {115, 127, 1}, },
            {{0, 110, -37}, {111, 111, 147}, {112, 127, 1}, },
            {{0, 96, -26}, {97, 97, 148}, {98, 127, 1}, },
            {{0, 113, -52}, {114, 114, 149}, {115, 127, 1}, },
            {{0, 100, -30}, {101, 101, 150}, {102, 127, 1}, },
            {{0, 115, -25}, {116, 116, 151}, {117, 127, 1}, },
            {{0, 96, -26}, {97, 97, 152}, {98, 127, 1}, },
            {{0, 109, -27}, {110, 110, 153}, {111, 127, 1}, },
            {{0, 109, -27}, {110, 110, 154}, {111, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 117, 1}, {118, 118, 155}, {119, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 109, -27}, {110, 110, 156}, {111, 127, 1}, },
            {{0, 96, -26}, {97, 97, 157}, {98, 127, 1}, },
            {{0, 100, -30}, {101, 101, 158}, {102, 127, 1}, },
            {{0, 100, -30}, {101, 101, 159}, {102, 127, 1}, },
            {{0, 110, -37}, {111, 111, 160}, {112, 127, 1}, },
            {{0, 113, -52}, {114, 114, 161}, {115, 127, 1}, },
            {{0, 113, -52}, {114, 114, 162}, {115, 127, 1}, },
            {{0, 110, -37}, {111, 111, 163}, {112, 127, 1}, },
            {{0, 110, -37}, {111, 111, 164}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 96, -26}, {97, 97, 165}, {98, 127, 1}, },
            {{0, 96, -26}, {97, 97, 166}, {98, 127, 1}, },
            {{0, 109, -27}, {110, 110, 167}, {111, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 99, -63}, {100, 100, 168}, {101, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 100, -30}, {101, 101, 169}, {102, 127, 1}, },
            {{0, 109, -27}, {110, 110, 170}, {111, 127, 1}, },
            {{0, 116, -32}, {117, 117, 171}, {118, 127, 1}, },
            {{0, 115, -25}, {116, 116, 172}, {117, 127, 1}, },
            {{0, 96, -26}, {97, 97, 173}, {98, 127, 1}, },
            {{0, 112, -54}, {113, 113, 174}, {114, 127, 1}, },
            {{0, 113, -52}, {114, 114, 175}, {115, 127, 1}, },
            {{0, 46, -3}, {48, 111, 1}, {112, 112, 176}, {113, 127, 1}, },
            {{0, 109, -27}, {110, 110, 177}, {111, 127, 1}, },
            {{0, 31, 1}, {32, 32, 178}, {33, 41, 1}, {43, 127, -3}, },
            {{0, 110, -37}, {111, 111, 179}, {112, 127, 1}, },
            {{0, 110, -37}, {111, 111, 180}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 108, -57}, {109, 109, 181}, {110, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 100, -30}, {101, 101, 182}, {102, 127, 1}, },
            {{0, 100, -30}, {101, 101, 183}, {102, 127, 1}, },
            {{0, 113, -52}, {114, 114, 184}, {115, 127, 1}, },
            {{0, 115, -25}, {116, 116, 185}, {117, 127, 1}, },
            {{0, 100, -30}, {101, 101, 186}, {102, 127, 1}, },
            {{0, 110, -37}, {111, 111, 187}, {112, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 116, -32}, {117, 117, 188}, {118, 127, 1}, },
            {{0, 96, -26}, {97, 97, 189}, {98, 127, 1}, },
            {{0, 104, -58}, {105, 105, 190}, {106, 127, 1}, },
            {{0, 96, -26}, {97, 97, 191}, {98, 127, 1}, },
            {{0, 100, -30}, {101, 101, 192}, {102, 111, 1}, {112, 112, 193}, {113, 113, 1}, {114, 114, 194}, {115, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 108, -57}, {109, 109, 195}, {110, 127, 1}, },
            {{0, 96, -26}, {97, 97, 196}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 100, -30}, {101, 101, 197}, {102, 127, 1}, },
            {{0, 100, -30}, {101, 101, 198}, {102, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 96, -26}, {97, 97, 199}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 115, -25}, {116, 116, 200}, {117, 127, 1}, },
            {{0, 110, -37}, {111, 111, 201}, {112, 127, 1}, },
            {{0, 109, -27}, {110, 110, 202}, {111, 127, 1}, },
            {{0, 96, -26}, {97, 97, 203}, {98, 127, 1}, },
            {{0, 100, -30}, {101, 101, 204}, {102, 127, 1}, },
            {{0, 111, -160}, {112, 112, 205}, {113, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 109, -27}, {110, 110, 206}, {111, 127, 1}, },
            {{0, 96, -26}, {97, 97, 207}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 112, -54}, {113, 113, 208}, {114, 127, 1}, },
            {{0, 113, -52}, {114, 114, 209}, {115, 127, 1}, },
            {{0, 111, -160}, {112, 112, 210}, {113, 127, 1}, },
            {{0, 96, -26}, {97, 97, 211}, {98, 127, 1}, },
            {{0, 115, -25}, {116, 116, 212}, {117, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 116, -32}, {117, 117, 213}, {118, 127, 1}, },
            {{0, 96, -26}, {97, 97, 214}, {98, 127, 1}, },
            {{0, 104, -58}, {105, 105, 215}, {106, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 110, -37}, {111, 111, 216}, {112, 127, 1}, },
            {{0, 96, -26}, {97, 97, 217}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 115, -25}, {116, 116, 218}, {117, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 109, -27}, {110, 110, 219}, {111, 127, 1}, },
            {{0, 96, -26}, {97, 97, 220}, {98, 127, 1}, },
            {{0, 115, -25}, {116, 116, 221}, {117, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 110, -37}, {111, 111, 222}, {112, 127, 1}, },
            {{0, 127, -3}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 71, 71, 71, 71, 16, 25, 7, 6, 8, 12, 10, 11, 24, 4, 67, 14, 13, 19, 22, 18, 72, 3, 5, 2, 15, 9, 72, 72, 72, 63, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 1, 0, 71, -1, 73, 70, -1, 17, 21, 23, 20, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 61, 72, 72, 72, 35, 72, 72, 72, 69, 70, 68, 72, 72, 72, 45, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 60, 72, 72, 72, 72, 72, 72, 72, 72, 29, 72, 72, 62, 72, 72, 41, 72, 72, 72, 72, 72, 44, 72, -1, 28, 72, 72, 54, 72, 72, 43, 72, 72, 32, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 36, 72, 65, -1, -1, -1, -1, 72, 72, 72, 72, 72, 56, 72, 72, 72, 38, 72, 66, 40, 72, 72, 72, 72, 72, -1, -1, -1, 37, 27, 72, 72, 33, 42, 72, 51, 72, 72, 72, 72, 72, 72, 55, -1, -1, -1, -1, -1, 31, 72, 72, 57, 64, 72, 72, 59, 48, -1, 47, -1, -1, -1, -1, -1, 72, 26, 34, 30, -1, -1, 39, -1, -1, -1, 72, -1, 53, -1, -1, -1, 58, -1, -1, 46, -1, 50, -1, -1, -1, 52, -1, 49, },
        // COMENTARIO_ANINHADO
        {75, 75, 16, 25, 7, 6, 8, 12, 10, 11, 24, 4, 67, 14, 13, 19, 22, 18, 3, 5, 2, 15, 9, 75, 75, 63, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 1, 0, 75, -1, 74, 73, 70, 75, 17, 21, 23, 20, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 61, 75, 75, 75, 35, 75, 75, 75, 69, 69, 70, 68, 45, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 60, 75, 75, 75, 75, 75, 75, 75, 75, 29, 75, 75, 62, 75, 75, 41, 75, 75, 75, 75, 75, 44, 75, 75, 28, 75, 75, 54, 75, 75, 43, 75, 75, 32, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 36, 75, 65, 75, 75, 75, 75, 75, 75, 75, 75, 75, 56, 75, 75, 75, 38, 75, 66, 40, 75, 75, 75, 75, 75, 75, 75, 75, 37, 27, 75, 75, 33, 42, 75, 51, 75, 75, 75, 75, 75, 75, 55, 75, 75, 75, 75, 75, 31, 75, 75, 57, 64, 75, 75, 59, 48, 75, 47, 75, 75, 75, 75, 75, 75, 26, 34, 30, 75, 75, 39, 75, 75, 75, 75, 75, 53, 75, 75, 75, 58, 75, 75, 46, 75, 50, 75, 75, 75, 52, 75, 49, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMENTARIO_ANINHADO = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
